### ISSUE TITLE
V138.1?

### ISSUE THREAD

**Issue by DatOnePlayer** [guiYMOUR/mindustry-Extra-Utilities-mod#19]
I cannot use the mod in said version, is this intentional or no?

**Comment by guiYMOUR** [comment]
try downloading the latest release, if it still doesn't work, i will continue to investigate

**Comment by DatOnePlayer** [comment]
I already did but it is not working

**Comment by DatOnePlayer** [comment]
I already did but it didn't do anything

**Comment by yesC48** [comment]
@guiyMOUR did you read the guide of how to migrate to v7 properly? maybe you missed a line and it caused Mindustry to go haywire.
