### ISSUE TITLE
thorium reactor 2 is not in the campaign tech tree

### ISSUE THREAD

**Issue by Rosnok** [guiYMOUR/mindustry-Extra-Utilities-mod#38]
![Mindustry_KBcCTkMqaf](https://github.com/guiYMOUR/mindustry-Extra-Utilities-mod/assets/124483595/5e226c0c-d775-41d4-b14f-e0743c2304e5)

i can see thorium reactor 2 in custom games but not in campaign tech tree, is this intended?

**Comment by guiYMOUR** [comment]
<img width="143" alt="image" src="https://github.com/guiYMOUR/mindustry-Extra-Utilities-mod/assets/77377005/f20e76ef-45d4-42c9-83d3-8f84e19f9385">

**Comment by guiYMOUR** [comment]
T2 Thorium Reactor: Sorry, maybe I don't look like myself...QAQ

**Comment by Rosnok** [comment]
> <img alt="image" width="143" src="https://private-user-images.githubusercontent.com/77377005/324167003-f20e76ef-45d4-42c9-83d3-8f84e19f9385.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MTA5NjUsIm5iZiI6MTcxMzYxMDY2NSwicGF0aCI6Ii83NzM3NzAwNS8zMjQxNjcwMDMtZjIwZTc2ZWYtNDVkNC00MmM5LTgzZDMtOGY4NGUxOWY5Mzg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDEwNTc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4M2NmYjFmNmQ0MmZkYTE4MWU4MGI5ODdhMjdiZmFjYjAxNWQ3MDE4YmYyNWMzYmU3NTYwMjg1M2FmOTIwMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LPBG0TYDIP3McYpoq5Eb6SMshkFZm7NBDt6TM1zEP9g">

Oh, apologies I used the wrong screenshot. I thought I had used the correct one, lol I should have double checked. I took that screenshot before I realized I only enabled Extra Utilities, I then proceeded to take another one (that is below) but forgot to upload it in the first place.

![javaw_KezwAlvsUi](https://github.com/guiYMOUR/mindustry-Extra-Utilities-mod/assets/124483595/9a91b521-ea1b-4fda-b893-39c49ca550a9)
But anyway, as you can see the Thorium Reactor II is missing in this tech tree, but after further troubleshooting while I was waiting for your response, I found out the culprit seems to be mod called Sapphirium. 

I don't know how or why another mod affect one block being prevented to appear in tech tree, I have played with many mods with Extra Utilities (such as Exogenesis, New Horizons, Upgraded Tiers, Expanded Industries and more) and they worked just fine with it. 
But Sapphirium appears to have a minor incompatibility that prevent this certain block from appearing in the tech tree. 

Screenshot below is when the aforementioned mod is disabled.
![javaw_zMHtdjTcOX](https://github.com/guiYMOUR/mindustry-Extra-Utilities-mod/assets/124483595/7678a19d-2503-404d-8f98-755b0af13e69)

But if I disregard this, everything in Extra Utilities appears in the tech tree even with Sapphirium enabled. I just dont know why Thorium Reactor II refuses to appear when the former mod is enabled.

**Comment by Rosnok** [comment]
If this problem really reside on Sapphirium's side instead of Extra Utilities' side then I will report this issue to their mod's repository and have this issue here closed. I can't really tell which is which because I am not a very good programmer, apologies. I would like to hear your thoughts on this issue before concluding.

**Comment by guiYMOUR** [comment]
If he overwrites the original tech tree, then I'm sorry, I can't do anything because the mod reading order is beyond my control. I try not to use overwrite, but instead use add to ensure the compatibility of other mods.

**Comment by guiYMOUR** [comment]
Perhaps you can send me the source code address of this mod
 so that I can see what it is for

**Comment by guiYMOUR** [comment]
It seems that his tech trees are all covered......

**Comment by Rosnok** [comment]
> Perhaps you can send me the source code address of this mod so that I can see what it is for

Sure, does this work for you? https://github.com/3Snake3/Sapphirium/tree/master

**Comment by guiYMOUR** [comment]
No, because he uploaded the compiled file, which is convenient for direct GitHub import...

**Comment by guiYMOUR** [comment]
I need to decompile it myself after downloading, TOO TROUBLESOME QAQ

**Comment by guiYMOUR** [comment]
anyway, I'll continue with my update work


> I need to decompile it myself after downloading, TOO TROUBLESOME QAQ

**Comment by Rosnok** [comment]
> No, because he uploaded the compiled file, which is convenient for direct GitHub import...

Hmmm.. I see, then I suppose this is unfixable on this side, it must be fixed on their side. Thanks for letting me take your time to explore this problem though.

**Comment by Rosnok** [comment]
> I need to decompile it myself after downloading, TOO TROUBLESOME QAQ

> anyway, I'll continue with my update work

I fully understand. It'd be a bit strange for another mod author to fix another one's mod lol, I'm not trying to impose anything just saying. I guess you shouldn't bother with it anymore then, I think it's best to focus on your mod :)
I'll try to see this problem in Sapphirium's side then. With that being said, I will close this issue now that the problem cannot be really fixed if their mod doesn't have their source code exposed. Have a good day :)
