### ISSUE TITLE
your edges are bleeding

### ISSUE THREAD

**Issue by BlueTheCube** [guiYMOUR/mindustry-Extra-Utilities-mod#39]
bleeding edge crash
[crash-report-05_12_2024_17_24_27.txt](https://github.com/guiYMOUR/mindustry-Extra-Utilities-mod/files/15285700/crash-report-05_12_2024_17_24_27.txt)

**Comment by guiYMOUR** [comment]
??????

**Comment by guiYMOUR** [comment]
<img width="611" alt="image" src="https://github.com/guiYMOUR/mindustry-Extra-Utilities-mod/assets/77377005/4579bf3c-bc8b-4ff9-86bf-382c99269627">
why?

**Comment by guiYMOUR** [comment]
maybe... should i do version adaptation?

**Comment by guiYMOUR** [comment]
O... OpenGL3.0?

**Comment by BlueTheCube** [comment]
anuke gonna port to new opengl

**Comment by BlueTheCube** [comment]
version adaptation :trollface:

**Comment by BlueTheCube** [comment]
no updates :trollface:
