### ISSUE TITLE
Small Core

### ISSUE THREAD

**Issue by DatOnePlayer** [guiYMOUR/mindustry-Extra-Utilities-mod#4]
@guiYMOUR 
Is that buildable in the campaign??

**Comment by guiYMOUR** [comment]
yes ... and ... what's wrong?

**Comment by DatOnePlayer** [comment]
I cannot find it on tech tree

**Comment by DatOnePlayer** [comment]
@guiYMOUR

**Comment by guiYMOUR** [comment]
![image](https://user-images.githubusercontent.com/77377005/126109044-6c921929-2dc1-4fb6-84e4-fe69259d04c8.png)
and you should pass the Extraction Outpost
![image](https://user-images.githubusercontent.com/77377005/126109283-c79c5019-96b4-4d00-8302-337f173e5751.png)

**Comment by guiYMOUR** [comment]
@DatOnePlayer

**Comment by DatOnePlayer** [comment]
That is why, omg..I haven't done that map before...
Thanks for the info didn't know I have to pass EO for that
