### ISSUE TITLE
The new version needs to be adapted

### ISSUE THREAD

**Issue by guiYMOUR** [guiYMOUR/mindustry-Extra-Utilities-mod#6]
Due to my academic reasons, the new version has not been released yet, resulting in the old version of the module does not adapt to the new version of the game. I will be in a hurry to update it. I hope you will understand

**Comment by Br0ad** [comment]
@guiYMOUR will it fix the planet gen?

**Comment by guiYMOUR** [comment]
@Br0ad Of course, I have already updated it (on steam), and github has been failing to upload due to my network problems, I will update it as soon as possible, sorry again.

**Comment by guiYMOUR** [comment]
I will close this issue as soon as I complete the update

**Comment by Br0ad** [comment]
@guiYMOUR I have been here playing your mod for a long time and I have found it to be one of the much better mods out there and its really fun. 
Keep up the good work Have don't be hard on yourself and if you need to focus on school do it and I will fully support you and the mod 👍😃

**Comment by guiYMOUR** [comment]
Thank you for your support. If you have any questions, please contact me. Thank you.
